name: TerraformApply

description: "Apply Terraform configuration"

inputs:
  stage:
    required: true
    default: "dev"
    description: "The stage to deploy the Terraform resources"
  terraform_path:
    required: true
    default: "terraform/"
    description: "The path to the Terraform configuration files"
  github-token:
    description: "The GitHub token used to interact with GitHub API"
    required: false
    default: ${{ github.token }}
  log_level:
    description: "The log level for Terraform"
    required: false
    default: "INFO"

runs:
  using: composite
  steps:
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::625377802426:role/terraform-service-deployment-iam-role-${{ inputs.stage }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: "us-east-1"
        output-credentials: true
      id: creds
    - name: get-tf-env-vars
      shell: bash
      run: |
        # Create a new file
        echo "" > ${{ github.workspace }}/env_file
        # Loop over all environment variables
        for var in $(compgen -v); do
          # If the variable starts with TF_VAR_
          if [[ $var == TF_VAR_* ]]; then
            # Write the variable and its value to the file
            echo "export $var=${!var}" >> ${{ github.workspace }}/env_file
          fi
        done
    - name: terraform-apply
      uses: addnab/docker-run-action@v3
      with:
        options:
          -e AWS_ACCESS_KEY_ID=${{ steps.creds.outputs.aws-access-key-id }}
          -e AWS_SECRET_ACCESS_KEY=${{ steps.creds.outputs.aws-secret-access-key }}
          -e AWS_SESSION_TOKEN=${{ steps.creds.outputs.aws-session-token }}
          -e GITHUB_TOKEN=${{ inputs.github-token }}
          -e GITHUB_OWNER=proxyserver2023
          -e DD_API_KEY=${{ env.DD_API_KEY }}
          -e DD_APP_KEY=${{ env.DD_APP_KEY }}
          -e TF_LOG=${{ inputs.log_level }}
          -v ${{ github.workspace }}:/work
          -v ${{ github.workspace }}/env_file:/env_file
          -w /work
        image: hashicorp/terraform
        run: |
          source /work/env_file
          cd /work/${{ inputs.terraform_path }}
          git config --global url."https://proxyserver2023:${GITHUB_TOKEN}@github.com/proxyserver2023".insteadOf "https://github.com/proxyserver2023"

          terraform init -backend-config=backend-${{ inputs.stage }}.tfvars
          terraform fmt -check
          terraform plan -var "stage=${{ inputs.stage }}" -out tfplan
          terraform apply -var "stage=${{ inputs.stage }}" -auto-approve
